runtime: python27
api_version: 1
threadsafe: true
skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?\..*$
 - ^\.local_storage/

libraries:
 - name: webapp2
   version: latest

handlers:
 - url: /_ah/queue/deferred
   script: google.appengine.ext.deferred.deferred.application
   login: admin
 - url: /admin/.*
   script: admin.app
   secure: always
   login: admin
 - url: /.*
   script: conductor.app
   secure: always
